### ISSUE TITLE
More helpful error messages

### ISSUE THREAD

**Issue by boxed** [klahnakoski/mo-logs#2]
```
Traceback (most recent call last):
  File "/Users/andersh/Projects/moz-sql-parser/tests/test_simple.py", line 113, in test_bad_select1
    self.assertRaises('Expected select', lambda: parse("se1ect A, B, C from dual"))
  File "/Users/andersh/Projects/moz-sql-parser/venv/lib/python2.7/site-packages/mo_testing/fuzzytestcase.py", line 69, in assertRaises
    cause=f
  File "/Users/andersh/Projects/moz-sql-parser/venv/lib/python2.7/site-packages/mo_logs/__init__.py", line 398, in error
    raise e
Except: ERROR: expecting an exception returning "Expected select" got something else instead
```

That's a deeply unhelpful message. You should print what that "something else" is.

**Comment by klahnakoski** [comment]
Thank you for this.  I copied this issue to moz-sql-parser, who is responsible for the poor message.
